spring:
  session:
    store-type: jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_server
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/authorization_server
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth.algashop.local:8081
        client:
          algashop-test-client:
            registration:
              client-id: algashop-test
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}testing123"
              scopes:
                - products:read
                - products:write
                - products:stock:write
                - categories:read
                - categories:write
                - invoices:read
                - invoices:write
                - credit-cards:read
                - credit-cards:write
                - orders:read
                - orders:write
                - customers:read
                - customers:write
                - shopping-carts:read
                - shopping-carts:write
                - users:read
                - users:write
            token:
              access-token-time-to-live: 15m
              access-token-format: self-contained # JWT
          algashop-ordering-service-client:
            registration:
              client-id: algashop-ordering-service
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}secret123"
              scopes:
                - products:read
            token:
              access-token-time-to-live: 5m
              access-token-format: self-contained # JWT
          algashop-ecommerce-web-client:
            registration:
              client-id: algashop-ecommerce-web
              client-secret: "{noop}ecommerce123"
              client-name: AlgaShop Ecommerce
              authorization-grant-types:
                - authorization_code
                - refresh_token
              client-authentication-methods:
                - client_secret_basic
              redirect-uris:
                - http://algashop.local:9080/login/oauth2/code/algashop-ecommerce-web
                - https://oauth.pstmn.io/v1/callback
              post-logout-redirect-uris:
                - http://algashop.local:9080?logout-success
              scopes:
                - credit-cards:read
                - credit-cards:write
                - orders:read
                - orders:write
                - customers:read
                - customers:write
                - shopping-carts:read
                - shopping-carts:write
                - openid
            require-authorization-consent: true
            require-proof-key: false #PKCE
            token:
              access-token-time-to-live: 5m
              authorization-code-time-to-live: 10m
              refresh-token-time-to-live: 1h
              reuse-refresh-tokens: false
          algashop-ecommerce-m2m-client:
            registration:
              client-id: algashop-ecommerce-m2m
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}m2m123"
              scopes:
                - products:read
                - categories:read
                - customers:write
            token:
              access-token-time-to-live: 15m
          algashop-admin-web-client:
            registration:
              client-id: algashop-admin-web
              client-name: AlgaShop Admin
              authorization-grant-types:
                - authorization_code
              client-authentication-methods:
                - none # Client público sem autenticação
              redirect-uris:
                - http://admin.algashop.local:4200
                - http://admin.algashop.local:4200/silent-refresh.html
                - https://oauth.pstmn.io/v1/callback
              post-logout-redirect-uris:
                - http://admin.algashop.local:4200
              scopes:
                - products:read
                - products:write
                - products:stock:write
                - categories:read
                - categories:write
                - invoices:read
                - orders:read
                - customers:read
                - shopping-carts:read
                - users:read
                - users:write
                - openid
            require-authorization-consent: false
            require-proof-key: true #PKCE
            token:
              access-token-time-to-live: 5m
              authorization-code-time-to-live: 2m

algashop:
  security:
    defaultRedirectUri: http://algashop.local:9080
    cors:
      allowedOrigins:
        - http://admin.algashop.local:4200
    cookie:
      secure: false # true = https
      sameSite: Lax #None, Lax, Strict
      domainName: algashop.local
    csp:
      policyDirectives: frame-ancestors 'self' http://admin.algashop.local:4200 http://auth.algashop.local:8081
logging:
  level:
    org.springframework.security: TRACE