spring:
  security:
    oauth2:
      authorizationserver:
        client:
          algashop-test-client:
            registration:
              client-id: algashop-test
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}testing123"
              scopes:
                - products:read
                - products:write
            token:
              access-token-time-to-live: 15m
              access-token-format: reference # OPAK
          algashop-ordering-service-client:
            registration:
              client-id: algashop-ordering-service
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}secret123"
              scopes:
                - products:read
            token:
              access-token-time-to-live: 15m
              access-token-format: self-contained # JWT