spring:
  datasource:
    url: jdbc:postgresql://algashop-postgres:5432/authorization_server
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
    user: postgres
    password: postgres
    url: jdbc:postgresql://algashop-postgres:5432/authorization_server